name: Trigger auto deployment for album-api

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ main ]
    paths:
    - 'src/**'
    - '.github/workflows/album-api-AutoDeployTrigger-3d9f9b3f-79fd-4c03-938a-aa29402499bc.yml'

  # Allow manual trigger 
  workflow_dispatch:
      
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.ALBUMAPI_AZURE_CREDENTIALS }}

      - name: Build and push container image to registry
        uses: azure/container-apps-deploy-action@v2
        with:
          appSourcePath: ${{ github.workspace }}/src 
          registryUrl: caf3e2e2c419acr.azurecr.io
          registryUsername: ${{ secrets.ALBUMAPI_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.ALBUMAPI_REGISTRY_PASSWORD }}
          containerAppName: album-api
          resourceGroup: album-containerapps
          imageToBuild: caf3e2e2c419acr.azurecr.io/album-api:${{ github.sha }}

  cleanup:
    runs-on: ubuntu-latest
    needs: build-and-deploy
    if: success()
    steps:
    - name: Check disk usage before cleanup
      run: df -h
    - name: Delete artifact
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        ARTIFACT_ID=$(curl -H "Authorization: token $GITHUB_TOKEN" \
        -H "Accept: application/vnd.github.v3+json" \
        https://api.github.com/repos/${{ github.repository }}/actions/artifacts \
        | jq -r '.artifacts[] | select(.name == "build-artifact") | .id')

        if [ -n "$ARTIFACT_ID" ]; then
          curl -X DELETE -H "Authorization: token $GITHUB_TOKEN" \
          -H "Accept: application/vnd.github.v3+json" \
          https://api.github.com/repos/${{ github.repository }}/actions/artifacts/$ARTIFACT_ID
        else
          echo "Artifact not found"
        fi
    - name: Check disk usage after cleanup
      run: df -h
            

     

